Task 01: Creating a Database and Table

CREATE DATABASE HAMAD_AHMED_LAB_TASK_04;

USE HAMAD_AHMED_LAB_TASK_04;

CREATE TABLE PUBLISHERS (
P_ID VARCHAR(4),
P_Name VARCHAR(30),
Address VARCHAR(40),
State VARCHAR(20),
Phone VARCHAR(20)
);

Task 02: Modifying Table Structure

ALTER TABLE PUBLISHERS
ADD Email_ID VARCHAR(20);

ALTER TABLE PUBLISHERS
ALTER COLUMN P_ID INT;

ALTER TABLE PUBLISHERS
ALTER COLUMN Phone INT;

Task 03: Renaming and Deleting Table

EXEC sp_rename 'PUBLISHERS', 'PUBLISHER';

DROP TABLE PUBLISHER;

Task 04: Creating and Modifying Another Table

CREATE TABLE BOOKS (
ISBN VARCHAR(4),
Book_Title VARCHAR(30),
Category VARCHAR(15),
Price NUMERIC(6,2),
Copyright_Date NUMERIC(4),
Year NUMERIC(4),
P_ID VARCHAR(4)
);
ALTER TABLE BOOKS
ADD Page_Count NUMERIC(4);

ALTER TABLE BOOKS
ALTER COLUMN ISBN INT;
ALTER TABLE BOOKS
ALTER COLUMN Copyright_Date VARCHAR(4);

Task 05: Deleting Tables and Database

DROP TABLE BOOKS;

USE master;
DROP DATABASE HAMAD_AHMED_LAB_TASK_04;
