
CREATE DATABASE hammad_ahmed_lab_task_05;

USE hammad_ahmed_lab_task_05;

CREATE TABLE PUBLISHERS (
    P_ID INT PRIMARY KEY,
    P_Name VARCHAR(30) NOT NULL,
    Address VARCHAR(50),
    State VARCHAR(12) DEFAULT 'Unknown',
    Phone VARCHAR(18) NOT NULL,
    Email_ID VARCHAR(20)
)


CREATE TABLE BOOKS (
    ISBN INT PRIMARY KEY,
    Book_Title VARCHAR(50) NOT NULL,
    Category VARCHAR(20),
    Price NUMERIC(6,2),
    Copyright_Date VARCHAR(4),
    Year NUMERIC(4),
    Page_Count NUMERIC(4),
    P_ID INT NOT NULL
);
ALTER TABLE BOOKS
ADD CONSTRAINT FK_BOOKS_PUBLISHERS
FOREIGN KEY (P_ID) REFERENCES PUBLISHERS(P_ID);
ALTER TABLE BOOKS
ADD CONSTRAINT CHK_BookPrice CHECK (Price > 20);
ALTER TABLE BOOKS
ADD CONSTRAINT UQ_BookTitle UNIQUE (Book_Title);
SELECT 
    TABLE_NAME, 
    CONSTRAINT_NAME, 
    CONSTRAINT_TYPE 
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE TABLE_NAME IN ('PUBLISHERS', 'BOOKS');

SELECT 
    CONSTRAINT_NAME, 
    TABLE_NAME, 
    COLUMN_NAME 
FROM INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE
WHERE TABLE_NAME IN ('PUBLISHERS', 'BOOKS');
  



ALTER TABLE PUBLISHERS
DROP CONSTRAINT DF__PUBLISHER__State__108B795B;
  

ALTER TABLE BOOKS
DROP CONSTRAINT CHK_BookPrice;
  








DROP TABLE PUBLISHERS;
ALTER TABLE BOOKS
DROP CONSTRAINT FK_BOOKS_PUBLISHERS;
  

DROP TABLE PUBLISHERS;
  
